# Baseline Configuration
# 基线配置

# Solver settings
solver:
  type: "control_grad"
  learning_rate: 1e-3
  num_iterations: 1000

# Network architecture  
network:
  type: "follmer_drift"
  hidden_dims: [64, 64]
  activation: "swish"

# Integration settings
integrator:
  type: "euler"
  dt: 0.01
  num_steps: 100

# TODO: Add complete configuration schema