# PhysioNet Dataset Configuration  
# PhysioNet数据集配置

# Dataset settings
dataset:
  type: "physionet"
  data_path: "./data/physionet"
  sequence_length: 48
  num_features: 37

# Training setup
training:
  batch_size: 32
  num_epochs: 100
  validation_split: 0.2

# TODO: Add PhysioNet-specific preprocessing configuration